package com.aiincident.logprocessor.rca;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Structured Root Cause Analysis (RCA) Report generated by the AI RCA Engine.
 * Explicitly distinguishes observed evidence, inference, and uncertainty.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public record RcaReport(
        RootCause rootCause,
        Confidence confidence,
        List<EvidenceItem> evidence,
        List<AlternativeHypothesis> alternativeHypotheses,
        AffectedServices affectedServices,
        List<RecommendedInvestigation> recommendedInvestigation,
        List<HistoricalReference> historicalReferences,
        List<String> uncertaintyNotes,
        RcaReportMetadata metadata,
        RcaValidationResult validation
) {

    public RcaReport(
            RootCause rootCause,
            Confidence confidence,
            List<EvidenceItem> evidence,
            List<AlternativeHypothesis> alternativeHypotheses,
            AffectedServices affectedServices,
            List<RecommendedInvestigation> recommendedInvestigation,
            List<HistoricalReference> historicalReferences,
            List<String> uncertaintyNotes,
            RcaReportMetadata metadata
    ) {
        this(rootCause, confidence, evidence, alternativeHypotheses, affectedServices, recommendedInvestigation, historicalReferences, uncertaintyNotes, metadata, null);
    }

    public RcaReport withValidation(RcaValidationResult validation) {
        return new RcaReport(
                this.rootCause,
                this.confidence,
                this.evidence,
                this.alternativeHypotheses,
                this.affectedServices,
                this.recommendedInvestigation,
                this.historicalReferences,
                this.uncertaintyNotes,
                this.metadata,
                validation
        );
    }

    /**
     * Statement and reasoning for the identified root cause.
     */
    public record RootCause(
            String statement,
            String category,
            String rootService,
            String inferenceDetails,
            boolean isDirectlyObserved
    ) {}

    /**
     * Confidence assessment based on completeness of available evidence.
     */
    public record Confidence(
            String level, // HIGH, MEDIUM, LOW
            double score, // 0.0 to 1.0
            String rationale
    ) {}

    /**
     * Specific operational evidence item supporting the analysis.
     */
    public record EvidenceItem(
            String type, // LOG, METRIC, ANOMALY, DEPLOYMENT, TOPOLOGY, TIMELINE
            String service,
            String observation,
            String sourceId,
            boolean isDirectObservation,
            Instant timestamp
    ) {}

    /**
     * Alternative hypothesis considered during root cause evaluation.
     */
    public record AlternativeHypothesis(
            String hypothesis,
            String likelihood, // HIGH, MEDIUM, LOW
            String reasonsForRejection,
            String missingEvidence
    ) {}

    /**
     * Breakdown of affected services, distinguishing root cause service from downstream symptoms.
     */
    public record AffectedServices(
            String rootService,
            List<String> symptomServices,
            Map<String, String> serviceImpacts
    ) {}

    /**
     * Concrete, evidence-grounded action recommended for investigation or remediation.
     */
    public record RecommendedInvestigation(
            String action,
            String priority, // IMMEDIATE, HIGH, MEDIUM, LOW
            String justification,
            String runbookRef
    ) {}

    /**
     * Historical incident or runbook cited as precedent.
     */
    public record HistoricalReference(
            String referenceId,
            String title,
            String similarityReason,
            String resolutionSummary
    ) {}

    /**
     * Metadata concerning the RCA report execution.
     */
    public record RcaReportMetadata(
            Instant analyzedAt,
            String provider,
            String model,
            long executionLatencyMs,
            String incidentIdentifier
    ) {}
}
